### ISSUE TITLE
Animations are not displayed properly in geyser

### ISSUE THREAD

**Issue by rewsdjad1** [Nutty101/NPCDestinations_Animation#15]
plugin version 2.6.10
server version paper-1.17.1-408

This plugin doesn't seem to be compatible with geyser, when NPCs are sitting they display fine in Java Edition, while in geyser (Bedrock Edition) NPCs are floating in the air.

Here is a Screenshot:
![Screenshot_20220317-202047_Minecraft](https://user-images.githubusercontent.com/79432245/158931602-1a0249f9-2aa1-4db1-9f2e-4d9e66762b3f.jpg)

**Comment by Nutty101** [comment]
I don't have any plans to support bedrock or crossovers. I would consider this plugin in maint only, and not actively being developed.
