### ISSUE TITLE
Problem with using an Animation addon on the older versions

### ISSUE THREAD

**Issue by IceMeltt** [Nutty101/NPCDestinations_Animation#4]
Hello,
I have some type of problem when I'm trying to use this plugin on the older minecraft versions (like on 1.13.3, 1.12.2, etc.). I'm using this plugin on my own as the reference of an API for NPC to make them sleep on the beds. When the plugin works correctly on the 1.14.4 (Citizens seems to be buggy on this version, so I have to use this plugin on the older versions), it doesn't work on the 1.12.2. It throws NullPointerExceptions everytime when I'm trying to use the `SleepNPC()` method.

StackTrace: https://pastebin.com/f2mqJQag

My code:
```java
Player player = (Player) event.getEntity();
NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.PLAYER, player.getName());

Bukkit.getScheduler().runTaskLater(this.plugin, () -> {
    Destinations_Animations.Instance.getNMSBridge.SleepNPC(npc, player, 0);
    location.getBlock().setType(Material.AIR);
            }, 15);
```

Server version: CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
OS: Windows 10

Thanks for any help! :)

**Comment by Nutty101** [comment]
Let me fire up a copy and see what the issue is. Be a bit, but I'll get back to you. Sleeping has been really funky of late.

**Comment by IceMeltt** [comment]
Well, as this code is my commision for the other guy, I'd prefer to send the link for this plugin to your any DM source. Can I send a copy on the file hosting site, and afterwards - a link for the copy on your email?

**Comment by Nutty101** [comment]
Are you on Discord? If so come find me in my channel and PM me or hit me up in the channel.  https://discord.gg/azTJ3z

**Comment by Nutty101** [comment]
Also, I would just snip the code off mine and tailer it to your needs.
`    // Sleeping Code
    @Override
    public void SleepNPC(NPC npc, Player player, float yaw) {
        final NPC thisNPC = npc;
        final Player plr = (Player) player;
        final NPCDestinationsTrait destTrait = thisNPC.getTrait(NPCDestinationsTrait.class);
        final EntityPlayer playerEntity = (EntityPlayer) getHandle(((Player) thisNPC.getEntity()));

        playerEntity.sleep(new BlockPosition(playerEntity), true);
    }

    @Override
    public void unsleepNPC(NPC npc) {
        EntityPlayer playerEntity = (EntityPlayer) getHandle(((Player) npc.getEntity()));
        playerEntity.wakeup(false,false,false);
    }

The older versions require packets to be sent, as well as placing a bed. They have to be slept onto a bed, then teleported around.

**Comment by IceMeltt** [comment]
`Are you on Discord? If so come find me in my channel and PM me or hit me up in the channel.`
Yeah, I have. Sure, I will write a direct message to you 🙂 

`Also, I would just snip the code off mine and tailer it to your needs.` I'll think about that, thanks for suggestion! 😉
